const PENDING_TABLE_HEADERS = [
  'Id',
  'Type',
  'Name',
  'Street',
  'Zipcode',
  'State',
  'Qb Vendor Name',
  'Qb City State Zip',
  'Primary Phone',
  'Backup Phone',
  'Primary Email',
  'Comments',
  'Fax phone',
  'Contact name',
  'Website',
  'Business hours',
  'Find out',
  'Onboarding status',
  'Join date',
  'Input type status',
  'Vendor type',
  'Status',
  'Pets of the homeless discount',
  'Updated by',
  'Updated date time',
  'Sync to qb',
  'Veterinary',
  'Ressoure',
  'Food',
  'Donation',
  'Family shelter',
  'Wellness',
  'Spray neuter',
  'Financial',
  'Re home',
  'Er boarding',
  'Senior',
  'Cancer',
  'Dog',
  'Cat',
  'Fph phone',
  'Contact phone',
  'Web notes',
  'Internal notes',
  'Published',
  'Shelter',
  'Domestic Violence',
  'Web Date Init',
  'Ent Qb',
  'Service Request',
  'Inactive',
  'Final Check',
  'Created By',
  'Created Date',
  'City',
  'Application',
];

export { PENDING_TABLE_HEADERS };
